name: falangthai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  app_links: ^6.4.1
  appinio_swiper: ^2.1.1
  audio_waveforms: ^1.3.0
  cached_network_image: ^3.4.1
  cherry_toast: ^1.13.0
  chewie: ^1.13.0
  emoji_picker_flutter: ^4.3.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: ^9.2.4
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.9.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get: ^4.7.2
  google_fonts: ^6.3.1
  google_sign_in: ^7.2.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  loading_indicator: ^3.1.1
  lottie: ^3.3.1
  onesignal_flutter: ^5.3.4
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^5.0.2
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  socket_io_client: ^3.1.2
  url_launcher: ^6.3.2
  video_compress: ^3.1.4
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/falang.png"    

flutter:
  uses-material-design: true
  assets:
    - assets/images/
